### ISSUE TITLE
Pass the file to replacer function?

### ISSUE THREAD

**Issue by lynchd6-emc** [brunobasto/karma-replacer-preprocessor#1]
It would be handy to have the file being processed when replacer is called:

``` javascript
var replacedContent = replacer(file, content);
```

This way I could test the file path and do different things to different files?

**Comment by brunobasto** [comment]
Yeah, I realized that couple hours after I wrote it. Will push this improvement soon.

**Comment by brunobasto** [comment]
@lynchd6-emc 

Changes pushed and published to npm.
